project_id = "ojgxyixgddhkceisbyjg"

[functions.create-pix-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.test-pix-payment]
verify_jwt = false
